# Generated by Django 5.0.14 on 2026-10-07 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Mascota')),
                ('especie', models.CharField(help_text='Ej: Perro, Gato, Ave', max_length=50)),
                ('raza', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.PositiveIntegerField(help_text='Edad en años')),
                ('precio', models.IntegerField(help_text='Precio mayor a 0', validators=[django.core.validators.MinValueValidator(1)])),
                ('stock', models.IntegerField(help_text='Stock no puede ser negativo', validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]